version: "3.3"
services:
    influxdb:
      container_name: influxdb
      image: influxdb
      ports:
       - "8086:8086"
       - "8083:8083"
      environment:
       - INFLUXDB_USER=root
       - INFLUXDB_PASS=root
       - INFLUXDB_NAME=stats
      volumes:
       - $PWD/data:/var/lib/influxdb
    grafana:
      image: fg2it/grafana-armhf:v5.1.3
      environment:    
       - NO_PROXY="influxdb"
      depends_on:
       - influxdb
      ports:
       - "3000:3000"

